### ISSUE TITLE
Nextcloud not working if media.peerconnection.enabled=false

### ISSUE THREAD

**Issue by FlorentCoppint** [nextcloud/jsxc.nextcloud#10] opened 2017-04-07 10:57 UTC
Hi everyone,

On Firefox, if I have the config "media.peerconnection.enabled" to false, the app is blocking everything on Nextcloud (can't login, and if I was already logged-in, can't display files).
Is it expected ? 
I know that app should not work with this setting, but it should not block others Nextcloud usages, on my mind.

Thank you.

**Comment by sualko** [comment] 2017-04-07 11:23
duplicate of jsxc/jsxc#471

**Closed by sualko** 2017-04-07 11:23 UTC
