### ISSUE TITLE
Beta 2 OMEMO encrypted communication not possible

### ISSUE THREAD

**Issue by drumdum** [nextcloud/jsxc.nextcloud#121] opened 2019-03-26 11:17 UTC
After installing the beta 2 and setting up everything in nextcloud, I am able to chat with different chat clients (gajim, pdgin, pixart messenger and conversations) if I disable OMEMO encryption.

With encryption enabled I receive an error message in jsxc stating:
      Error: Could not encrypt data with any Signal session

Trying to send an encrypted message to jsxc leads to a message generated by the chat clients that jsxc is not capable of OMEMO encryption. The message is dependant on the chat client, gajim sends:

     You received a message encrypted with OMEMO but your client doesn't support OMEMO.

So it seems like the initiation of the encrypted session does not work. I like jsxc very much and it concludes my all in one secure and private collaboration platform for my family and friends, but with end to end xmpp communication it would even be better. Thanks for the work on this simple but powerful tool. If I can help testing any further please let me know.

**Comment by sualko** [comment] 2019-03-26 12:29
Which XMPP server do you use? Do you have any errors in your js console? Can you enable jsxc debug mode and post the log? Just call `ojsxc.jsxc.enableDebugMode()` and reload.

**Comment by drumdum** [comment] 2019-03-28 11:33
I use Prosody 0.10.2 on freebsd. Thanks for the hint on the js console. 

After enabling the debug mode I tried to send an encrypted message to jsxc but got no entry in the console. I first had to verify all the keys again. See the attached image of the conversation i tested.

![Auswahl_003](https://user-images.githubusercontent.com/14397336/55154314-c2464a80-5154-11e9-9617-a4a7d712cbfd.png)

Sending messages from jsxc threw some errors in the console as yoou can see from the attached log.

[jsxc_nextcloud_omemo.log](https://github.com/nextcloud/jsxc.nextcloud/files/3017672/jsxc_nextcloud_omemo.log)

I've just replaced the hostnames of the servers and something I thought could be an omemo key. Apart from that it is the complete log of the js console for the pictured conversation.

As the other client I used Pix-Art messenger on Android.

**Comment by sualko** [comment] 2019-03-28 20:23
I guess it's related to `Could not encrypt data for device with id xxxxx Error: "Identity key changed"`. Another thing is that the log is from a slave tab, so maybe there is an issue if you start omemo not in the master tab. I will look into that asap. If you like you can try to clear your localstorage and retry it with only one tab.

**Comment by drumdum** [comment] 2019-04-01 19:14
Just tried to chat encrypted with only one tab open after clearing all cache and local browser data. But unfortunately it is not working with exactly the same type of error. What I've discovered while fiddling around with jsxc is that the pidgin lurch plugin also has problems sending encrypted messages since the introduction of jsxc as a xmpp client. Maybe there is a connection.

Thanks for looking at this. If there is anything else I can do to help you catch this just give me a ping.

**Comment by sualko** [comment] 2019-04-09 09:13
> If there is anything else I can do to help you catch this just give me a ping.

I currently have no clue how we could debug this. I will try to reproduce this with pidgin/JSXC and maybe I have to introduce some more debug information. A dialog or something different. If your XMPP server allows s2s, it would be great if you could add me (klaus@jsxc.org), so I can make some tests.

**Comment by Luticus** [comment] 2019-04-18 14:58
I have some experience with trying to use lurch with pidgin and even adium on mac and in either case my results were not good. This could easily be an issue with lurch and not with jsxc. I use the conversations app on my phone and pidgin/lurch doesn't seem to like it. I would test between conversations and jsxc and see if you get better results. I'll try to test all 3 out, maybe later today. I was trying to wait for the stable release but I do have a test server so maybe I could set something up there and help that way. Anyhow, just my 2 cents on the subject.

**Comment by sualko** [comment] 2019-04-23 12:53
> I'll try to test all 3 out, maybe later today.

Did you have time to do some tests? Would be awesome to have some more cents :wink:. Can confirm your experience with lurch and other clients. It's quite difficult to find a "good" client which fits all your needs, but maybe JSXC can fill that gap one day.

**Comment by Luticus** [comment] 2019-04-24 13:30
Yea I'll see if I can maybe get to trying it out tonight.  I had work+family+life hold me up this week a bit so I haven't had time to update my test nextcloud box and install the beta.  I guess I could just throw the beta on the main server.  We have the conversations app to fall back on and I can always downgrade jsxc if there's a major issue.  I'll give that a try and see if I can get you some feedback.

**Comment by Luticus** [comment] 2019-04-24 20:39
Well I tried to test it but when i got it set up it didn't show any interface on the right like it normally would.  I noticed in the logs it was complaining about a file missing:  Could not find resource file \"\/apps\/ojsxc\/js\/config.js\"  

I'll try to work with it a bit later tonight.  Might be creating an issue for it unless you know a quick fix or something.

**Comment by sualko** [comment] 2019-04-25 08:14
@Luticus Thanks for testing and sorry that you had some trouble, but the good news is, that this has already been fixed: a67de8febb9327ad2332cfbe82143bfc8994e726

**Comment by Luticus** [comment] 2019-04-26 03:21
I agree with the OP.  Something is wrong with OMEMO.   I think perhaps the keys/fingerprints aren't being exchanged properly perhaps.  When I try to send a message from ojsxc I get an unencrypted message in conversations, when I try to send from conversations to ojsxc I get an error that asks me to disable encryption.

**Comment by Luticus** [comment] 2019-04-28 11:38
Ok, few more comments on the subject.  I upgraded my servers to NC16 and tested there.  I noticed a few things.  First when I select OMEMO devices from the ... drop down menu i get this:


OMEMO devices

With OMEMO you can send an encrypted message to all OMEMO capable devices of you and your contact. To ensure that those devices really belong to you or your contact, you should compare their key IDs over another communication channel. If you don't want to compare those IDs, just click "Recognize", but please be aware that in this case someone could read along.

OMEMO devices of your contact
No devices available

Your own OMEMO devices
No devices available

Which I'm using conversations with OMEMO as my encryption method, and I know that works. 


When I try to enable OMEMO in ojscx I get:  Error your contact does not support OMEMO

I don't see any output in the nextcloud log when I try to mess with OMEMO settings.

Also when I log in to Nextcloud, ojsxc does not auto login as it has in the past, i noticed that on NC15 as well.  In addition, when I log in with 2fa totp or u2f apps enabled the ojsxc client pops out from the right during the 2fa authentication process, which it probably shouldn't do.  

Lastly when I try to send an image attachment, it says "attachment was not processed"

**Comment by sualko** [comment] 2019-05-06 13:37
> I don't see any output in the nextcloud log when I try to mess with OMEMO settings.

The javascript log would be interesting, specially all exchanged xmpp stanzas. Otherwise I can't debug this. If you like you can send the log to klaus@jsxc.org, or you can add me as xmpp contact, so that I can try it by my own.

> Also when I log in to Nextcloud, ojsxc does not auto login as it has in the past

It's not NC 16 ready. Sorry.

> Lastly when I try to send an image attachment, it says "attachment was not processed"

Please open a new issue for that including your js log.

**Comment by Luticus** [comment] 2019-05-06 14:19
Would be happy to send that log to you or to federate and add you as a contact.  My server does not currently federate though, but that's something I can change.  Anyway, I'll see if I can get that log to you.  

It's a shame it's not NC16 ready, but that's all good.  I'm sure that'll happen at some point.

I'll see if I can get a new issue open tonight when I get home from work.  Thanks!

**Comment by Luticus** [comment] 2019-05-07 11:38
Actually I need to retest some things.  I have updated my ejabberd server because the one that ships in Debian Stretch is very out dated.  Fortunately they have a much newer version in backports that I have just installed.  I tested with lurch and conversations yesterday and things went much better, although not perfect.  I will be testing ojsxc tonight to see if there are any improvements with the omemo support.

**Comment by sualko** [comment] 2019-05-07 11:55
Really appreciate your effort :+1:

**Comment by Luticus** [comment] 2019-05-07 20:30
Ok, so in NC in ojsxc 4 I get this error when I send or receive omemo messages in the java console in firefox:  
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 120:
XML Parsing Error: not well-formed
Location: 
Line Number 1, Column 120:

When I attempt to enable debug mode in the java console I get:  ReferenceError: jsxc is not defined[Learn More] debugger eval code:1:1

**Comment by sualko** [comment] 2019-05-08 07:32
> XML Parsing Error: not well-formed

The snippet which produces the error would be helpful.

> ReferenceError: jsxc is not defined

Try `ojsxc.jsxc.enableDebugMode()`. Due to the new api design, jsxc not longer exposed to the global namespace.

**Comment by sualko** [comment] 2019-05-09 08:42
> I can't seem to enable debug mode in the console

Is there any error, because that would be the easiest solution. The nextcloud log will not show any xmpp output. Otherwise you can view the traffic in the network tab of your debugging console.

**Comment by Luticus** [comment] 2019-05-09 12:22
I'll look into that.  Have to switch back to the beta version when I get home and test it out.

**Comment by Luticus** [comment] 2019-05-12 13:00
I also received this error in the java console:  Unhandled promise rejection 
<iq id="e173473d-2cb2-4a64-a77d-df444e68659d:sendIQ" xml:lang="en" to="joe@example.com/Nextcloud" from="joe@example.com" type="error" xmlns="jabber:client">es6.promise.js:110
    t es6.promise.js:110
    exports _perform.js:3
    O es6.promise.js:104
    exports _invoke.js:5
    <anonymous> _task.js:35
    v _task.js:21
    y _task.js:25

as well as this:  Source map error: request failed with status 404
Resource URL: https://www.example.com/index.php/js/spreed/merged-files.js?v=226de2c5-58
Source Map URL: backbone.marionette.min.js.map[Learn More]

and lastly I also saw this:  [Info] <iq xml:lang="en" to="joe@example.com/Nextcloud" from="joe@example.com" type="error" id="97110402-bafa-454e-924a-01e7543ec70b:sendIQ" xmlns="jabber:client"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="storage:bookmarks"/></pubsub><error code="405" type="cancel"><closed-node xmlns="http://jabber.org/protocol/pubsub#errors"/><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

**Comment by sualko** [comment] 2019-05-13 12:30
I think only the first error is OMEMO related. Which browser do you use? Can you post the full path of `es6.promise.js`?

**Comment by Luticus** [comment] 2019-05-15 14:20
Oddly when I use locate es6.promise.js it comes back with something from passman.  I need to retest this, maybe tonight and see what happens when I 1) disable the app, 2) use a new version of that app.  Are you going to be doing a 3rd beta of jsxc anytime soon?

**Comment by sualko** [comment] 2019-05-16 08:31
> Are you going to be doing a 3rd beta of jsxc anytime soon?

Hopefully next week and thanks for testing.

**Comment by sualko** [comment] 2019-05-23 12:17
Here you go: https://github.com/jsxc/jsxc/releases/tag/v4.0.0-beta.3

There is no new nextcloud version yet, but you can just replace the jsxc folder inside ojsxc/js/.

**Comment by Luticus** [comment] 2019-05-23 12:57
That's awesome.  That'll make testing a bit easier.  I'm hoping I can start doing it again tonight.  I just updated several other apps including passman, so now is a great time.  Hopefully we can figure this out.  Omemo is pretty much the single most important feature in 4.x for me.  :)

**Comment by sualko** [comment] 2019-05-23 13:21
> Omemo is pretty much the single most important feature in 4.x for me.

I think you are not alone. We successfully tested OMEMO now with Gajim, Dino and Conversations. Hope this works for you too.

**Comment by magoralczyk** [comment] 2019-06-07 14:05
I tried the ojsxc beta 2 with the js folder of jsxc beta 3 on nc 16.01, and the client makes the login, loads the roster along with the online status of the people, but when i click on anyone to chat with, only the header of the chatwindow shows on the bottom of the browser, and all I can do is close these "windows" again.

**Comment by sualko** [comment] 2019-06-09 14:12
@magoralczyk please open a new issue at https://github.com/jsxc/jsxc/issues and provide all the required logs.

**Comment by sualko** [comment] 2019-06-09 14:15
Btw I think I found the cause of the original issue here and therefore I close this ticket.

see jsxc/jsxc@80a0a55d0b6df997fea23ad0f11ffe3e1e28e066

**Closed by sualko** 2019-06-09 14:15 UTC
Labels: bug

**Comment by drumdum** [comment] 2019-08-13 07:53
I just tested beta 4 in Nextcloud and OMEMO encryption works like a charm. Thank you! Now Nextcloud got even better with a strong encrypted and easy to use chat communication based on XMPP. Keep up your great work.
