### ISSUE TITLE
Could not enable 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/jsxc.nextcloud#155] opened 2020-06-23 18:36 UTC
Installed the app. When enabling I get an error. The log gives

[index] Error: Exception: XMLWriter::writeAttribute() expects parameter 2 to be string, null given at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
4. /var/www/nextcloud/lib/base.php line 1007
   OC\Route\Router->match("/settings/apps/enable")
5. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /settings/apps/enable

and

[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ojsxc.javascript.generalConfig" as such route does not exist. at <<closure>>

 0. /var/www/nextcloud/lib/private/Route/Router.php line 338
    Symfony\Component\Routing\Generator\UrlGenerator->generate("ojsxc.javascript.generalConfig", [], 1)
 1. /var/www/nextcloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("ojsxc.javascript.generalConfig", [], false)
 2. /var/www/nextcloud/lib/private/URLGenerator.php line 83
    OC\Route\CachingRouter->generate("ojsxc.javascript.generalConfig", [])
 3. /var/www/nextcloud/apps/ojsxc/appinfo/app.php line 26
    OC\URLGenerator->linkToRoute("ojsxc.javascript.generalConfig")
 4. /var/www/nextcloud/lib/private/legacy/OC_App.php line 266
    require_once("/var/www/nextcl ... p")
 5. /var/www/nextcloud/lib/private/legacy/OC_App.php line 155
    OC_App::requireAppFile("ojsxc")
 6. /var/www/nextcloud/lib/private/legacy/OC_App.php line 961
    OC_App::loadApp("ojsxc")
 7. /var/www/nextcloud/lib/private/Installer.php line 160
    OC_App::executeRepairSteps("ojsxc", {step: "OCA\\OJS ... "})
 8. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 447
    OC\Installer->installApp("ojsxc")
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["ojsxc"], [])
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
11. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
12. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
13. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
14. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
15. /var/www/nextcloud/lib/base.php line 1007
    OC\Route\Router->match("/settings/apps/enable")
16. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

POST /settings/apps/enable
from 192.168.1.1 by NCadmin at 2020-06-23T20:33:21+02:00

NC 19.0. Nginx, Ubuntu 18.04,

**Comment by sualko** [comment] 2020-06-24 12:11
Sorry for having trouble installing this app. It seems like this could be a duplicate of jsxc/jsxc#916, therefore I close this issue and beg you to post there your setup (php version, db vendor and version, nc version, ...).

**Closed by sualko** 2020-06-24 12:11 UTC
