### ISSUE TITLE
"User xxxxxx-xxxxxx-xxxxx-xxxxx is trying to send a message to xxxxxx-xxxxxx-xxxxx-xxxxx but this isn´t allowed

### ISSUE THREAD

**Issue by hectorpuello** [nextcloud/jsxc.nextcloud#114] opened 2018-11-22 18:07 UTC
The issue consist: when users from ldap whom are conected to the  xmpp chat on nextcloud in a internal enviroment and they appear to be "online", the message doesn´t get sended, it just keep on the receiver.

![image](https://user-images.githubusercontent.com/38078312/48917921-bde4ea80-ee5f-11e8-8f6d-7e314e931b35.png)

Log Attached
[nextcloud.log](https://github.com/nextcloud/jsxc.nextcloud/files/2609008/nextcloud.log)

**Comment by sualko** [comment] 2018-11-27 14:42
cc @LEDfan

**Comment by Ristoune** [comment] 2019-08-19 10:05
Hi, I've the same problem with Nextcloud 15.0.8 and JSXC plugin 3.4.4

I've 2 LDAPs servers configured and when I'm talking with an user I've this message in the log : 

`{"reqId":"yGXgJsJt70mcAS4Eyf5r","level":2,"time":"2019-08-19T09:45:17+00:00","remoteAddr":"10.1.254.4","user":"KERH","app":"ojsxc","method":"POST","url":"\/nextcloud\/apps\/ojsxc\/http-bind","message":"User KERH is trying to send a message to jgre but this isn't allowed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"15.0.8.1"}`

Do you have any solution for this problem ?

THX

**Comment by AdamVenn** [comment] 2020-05-07 15:10
+1 for this. To clarify the issue, it is not allowed to _send_ messages to AD users. AD users can send messages to local users no problem.
I would love if it this were 'allowed'! Any explanation/workarounds?

**Comment by sualko** [comment] 2020-05-08 13:48
Hi everyone,
sorry that you encountered this issue, but the internal backend was only designed for small instances and an instance with ldap or ad is no small instance from our perspective and therefore we don't test this setup.

> Since this is explicitly forbidden and logged by line 76 in lib/stanzahandlers/message.php, I expect there is a good reason! Can anyone offer any explanation/workaround?

Chatting can be restricted, see https://github.com/jsxc/jsxc/wiki/Restrict-chatting-(Nextcloud-internal). Therefore this option.

The root cause of this issue is probably that the wrong uid is used, so that the system can't find the user. See https://github.com/nextcloud/jsxc.nextcloud/blob/9bebfe6fd82e04d3060778ba6380752199eb2d50/lib/UserManagerUserProvider.php#L51-L54

If you are brave you can try to change that function so that it just returns `true`, but the better solution would be to setup your own xmpp server (e.g. prosody/ejabberd) which is super easy and has a lot more features compared to the internal backend.

If you find a nice fix, we would appreciate a pull request. While we consider this setup out of scope for our small internal backend, I close this issue.

**Closed by sualko** 2020-05-08 13:48 UTC
Labels: bug
