### ISSUE TITLE
Chat authentication doesn't work properly

### ISSUE THREAD

**Issue by Emi94** [nextcloud/jsxc.nextcloud#58] opened 2017-08-17 13:20 UTC
Hi,

I have a Nextcloud 12.0.2 server with jsxc 3.2.1 app. Nextcloud has user_saml enabled using an environment variable and also a LDAP connection for user information retrieval (like email, full name).

When i login to Nextcloud and open the chat app i get "No connection! relogin". If i click relogin and enter my user/pass i get "Authentication failed with the chat server. Maybe the password is wrong?" even if user/pass are correct. But after this if i reload the page the chat app just logs me in. This works even if i provide wrong user/pass on the relogin.

Could this be fixed so that the chat app logs users in automatically?

**Comment by Emi94** [comment] 2017-08-18 09:11
internal

**Comment by sualko** [comment] 2017-08-18 09:12
Please set your log level to debug and post the related output, so that @LEDfan can review it.

**Comment by Emi94** [comment] 2017-08-18 12:18
the only thing the logs show is this:

`{"reqId":"G89gwj8n357K4m2MBvm4","level":0,"time":"2017-08-18T10:52:02+00:00","remoteAddr":"192.168.0.91","user":"test.user","app":"user_ldap","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"initializing paged search for  Filter (&(|(objectclass=person))(|(|(memberof=CN=Domain Users,CN=Users,DC=mydomain,DC=com)(primaryGroupID=513)))) base Array\n(\n    [0] => cn=test.user,cn=users,DC=mydomain,DC=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.78 Safari\/537.36 OPR\/47.0.2631.39","version":"12.0.2.0"}
{"reqId":"G89gwj8n357K4m2MBvm4","level":0,"time":"2017-08-18T10:52:02+00:00","remoteAddr":"192.168.0.91","user":"test.user","app":"user_ldap","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"Ready for a paged search","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.78 Safari\/537.36 OPR\/47.0.2631.39","version":"12.0.2.0"}
{"reqId":"G89gwj8n357K4m2MBvm4","level":0,"time":"2017-08-18T10:52:02+00:00","remoteAddr":"192.168.0.91","user":"test.user","app":"user_ldap","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"readAttribute: cn=test.user,cn=users,DC=mydomain,DC=com found","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.78 Safari\/537.36 OPR\/47.0.2631.39","version":"12.0.2.0"}`

which keeps repeating

**Comment by LEDfan** [comment] 2017-08-22 05:08
I have setup Kerberos and I can reproduce the issue. 

The problem is that JSXC starts the connecting when submitting the login form, however when using SSO there is no login from and thus also no way to access the username and password. However for the internal backend the username and password aren't needed.
@sualko do you have an idea how to solve this the best way?

**Comment by sualko** [comment] 2017-08-22 08:44
@LEDfan The internal server doesn't need username/password, so I don't understand the issue. If he uses the login box it should work as expected, or not?

**Comment by LEDfan** [comment] 2017-08-24 06:06
@sualko I was a bit unclear... What I meant to say is that the initialization process of JSXC isn't started because there is isn't a login form which is submitted. 
The user can press the relogin button in the roster, but this will send some authentication process to the internal backend, which it doesn't correctly replies to (which maybe should be fixed too). 

So my question is how we can solve the issue that the JSXC isn't started.

**Comment by LEDfan** [comment] 2017-09-09 15:28
@Emi94 I setup a test environment and made some changes to the bootstrap code. The changes are in #67, if you have a moment can you test if it works for you? I'll attach a build to the PR.

**Comment by Emi94** [comment] 2017-09-13 12:55
@LEDfan I'll try to test it this week and come back with the results

**Comment by Emi94** [comment] 2017-09-14 14:37
I tested the build you attached and it works, when i login to Nextcloud i automatically get logged to the chat app too, thx for the fix.

**Closed** 2017-10-19 17:02 UTC
Labels: waiting for pr
